import type { Color, VetorInfo, SumulaInfo, PrescricaoFaixa, ListItem } from "./types";

export const VETORES: VetorInfo[] = [
  { name: "Culpabilidade", art: "Art. 59, CP",
    desc: "Grau de reprovabilidade da conduta. Avalia a intensidade do dolo, a consciência da ilicitude e o nível de exigibilidade de conduta diversa. Não se confunde com culpabilidade como elemento do crime.",
    desfavoravel: "Dolo direto de elevada intensidade, premeditação acentuada, persistência na conduta ilícita, alta exigibilidade de conduta diversa.",
    alerta: "Não confundir com reincidência (2ª fase) nem com circunstâncias do crime. Elementos já usados como qualificadora não podem fundamentar este vetor." },
  { name: "Antecedentes", art: "Art. 59, CP",
    desc: "Vida pregressa criminal do réu. Considera condenações transitadas em julgado que não configurem reincidência (fora do período depurador de 5 anos — art. 64, I, CP).",
    desfavoravel: "Condenações anteriores transitadas em julgado que não gerem reincidência (período depurador expirado). Folha de antecedentes é suficiente (Súmula 636/STJ).",
    alerta: "Súmula 444/STJ: vedado uso de inquéritos e ações sem trânsito em julgado. Súmula 241/STJ: reincidência não pode ser agravante e circunstância judicial simultaneamente." },
  { name: "Conduta Social", art: "Art. 59, CP",
    desc: "Comportamento do réu no trabalho, família e comunidade. Avalia sua inserção social, relações familiares e vida profissional.",
    desfavoravel: "Histórico de condutas antissociais comprovadas nos autos, conflitos familiares graves, comportamento comunitário nocivo.",
    alerta: "Exige prova concreta. Meras suposições, estigmas sociais ou ausência de prova não fundamentam vetor negativo. Risco de estereotipagem." },
  { name: "Personalidade", art: "Art. 59, CP",
    desc: "Traços de caráter e temperamento revelados pelo comportamento: agressividade, impulsividade, frieza, calculismo.",
    desfavoravel: "Personalidade voltada ao crime, frieza durante execução, crueldade, calculismo extremo evidenciado nos autos.",
    alerta: "Vetor muito criticado doutrinariamente (direito penal do autor). Exige fundamento concreto. Alto risco de bis in idem com culpabilidade e circunstâncias do crime." },
  { name: "Motivos", art: "Art. 59, CP",
    desc: "Razão determinante da prática criminosa. Motivo torpe ou fútil agrava; motivo nobre pode favorecer; razão egoística neutra.",
    desfavoravel: "Motivo torpe, fútil, ganância excessiva, vingança desproporcional, discriminação.",
    alerta: "Verificar se o motivo já é elementar do tipo ou qualificadora (ex: motivo fútil no homicídio qualificado). Neste caso, vetor neutro — bis in idem." },
  { name: "Circunstâncias do Crime", art: "Art. 59, CP",
    desc: "Modo, lugar, tempo, instrumentos e demais aspectos que cercam o fato. Caráter residual — tudo que não se enquadra nas demais.",
    desfavoravel: "Modus operandi especialmente gravoso, local estratégico para dificultar socorro, tempo escolhido para facilitar impunidade.",
    alerta: "Não usar fatos que já fundamentam qualificadoras, majorantes ou outras circunstâncias judiciais. Bis in idem é o erro mais frequente neste vetor." },
  { name: "Consequências do Crime", art: "Art. 59, CP",
    desc: "Resultados concretos do crime além dos elementos do tipo penal. Dano moral, patrimonial, social acima do normal do delito.",
    desfavoravel: "Dano excepcionalmente elevado, sequelas permanentes, impacto social amplo, número elevado de vítimas.",
    alerta: "Consequências inerentes ao tipo não podem ser usadas (ex: morte no homicídio, subtração no furto). Apenas o que extrapola o resultado típico normal." },
  { name: "Comportamento da Vítima", art: "Art. 59, CP",
    desc: "Contribuição da vítima para o crime. Tipicamente favorável ao réu (quando houve provocação) ou neutro.",
    desfavoravel: "Raramente desfavorável ao réu. Vetor quase sempre neutro ou favorável.",
    alerta: "Se a vítima contribuiu para o crime, este vetor é FAVORÁVEL ao réu. Não usar negativamente sem fundamento sólido — seria punir o acusado pelo comportamento alheio." },
];

export const AGRAVANTES_LIST: ListItem[] = [
  { code: "Art. 61, I", desc: "Reincidência" },
  { code: "Art. 61, II, a", desc: "Motivo torpe" },
  { code: "Art. 61, II, b", desc: "Motivo fútil" },
  { code: "Art. 61, II, c", desc: "Facilitar ou assegurar execução, ocultação ou impunidade de outro crime" },
  { code: "Art. 61, II, d", desc: "Traição, emboscada, dissimulação ou recurso que dificultou a defesa" },
  { code: "Art. 61, II, e", desc: "Emprego de veneno, fogo, explosivo, tortura ou meio cruel" },
  { code: "Art. 61, II, f", desc: "Contra ascendente, descendente, irmão ou cônjuge" },
  { code: "Art. 61, II, g", desc: "Abuso de autoridade, relação doméstica, coabitação ou hospitalidade" },
  { code: "Art. 61, II, h", desc: "Abuso de poder ou violação de dever de cargo, ofício, ministério ou profissão" },
  { code: "Art. 61, II, i", desc: "Contra criança, maior de 60 anos, enfermo ou mulher grávida" },
  { code: "Art. 61, II, j", desc: "Quando o ofendido estava sob proteção imediata da autoridade" },
  { code: "Art. 61, II, l", desc: "Em ocasião de incêndio, naufrágio, inundação ou calamidade pública" },
  { code: "Art. 61, II, m", desc: "Em estado de embriaguez preordenada" },
  { code: "Art. 62, I", desc: "Promoveu ou organizou a cooperação no crime" },
  { code: "Art. 62, II", desc: "Coagiu ou induziu outrem à prática do crime" },
  { code: "Art. 62, III", desc: "Instigou ou determinou a cometer o crime" },
  { code: "Art. 62, IV", desc: "Executou mediante paga ou promessa de recompensa" },
];

export const ATENUANTES_LIST: ListItem[] = [
  { code: "Art. 65, I", desc: "Menor de 21 anos na data do fato" },
  { code: "Art. 65, I", desc: "Maior de 70 anos na data da sentença" },
  { code: "Art. 65, II", desc: "Desconhecimento da lei" },
  { code: "Art. 65, III, a", desc: "Motivo de relevante valor social ou moral" },
  { code: "Art. 65, III, b", desc: "Arrependimento eficaz ou arrependimento posterior" },
  { code: "Art. 65, III, c", desc: "Coação resistível ou cumprimento de ordem de superior hierárquico" },
  { code: "Art. 65, III, d", desc: "Confissão espontânea da autoria (Súmula 545/STJ)" },
  { code: "Art. 65, III, e", desc: "Influência de multidão em tumulto" },
  { code: "Art. 66", desc: "Circunstância relevante anterior ou posterior ao crime (inominada)" },
];

export const MAJORANTES_LIST: ListItem[] = [
  { code: "Art. 157, § 2º, I", desc: "Roubo com emprego de arma" },
  { code: "Art. 157, § 2º, II", desc: "Roubo com resultado lesão grave ou morte" },
  { code: "Art. 14, § 1º", desc: "Concurso de pessoas (coautoria/participação)" },
  { code: "Art. 71", desc: "Concurso formal de crimes" },
  { code: "Art. 70", desc: "Concurso material de crimes (acréscimo de 1/6 a 2/3)" },
  { code: "Lei 8.072/1990", desc: "Crime hediondo ou equiparado (aumento de 1/3 a 1/2)" },
  { code: "Art. 240, § 1º", desc: "Furto qualificado com emprego de arma" },
  { code: "Art. 121, § 2º", desc: "Homicídio qualificado" },
  { code: "Art. 129, § 2º", desc: "Lesão corporal gravíssima" },
  { code: "Art. 148, § 1º", desc: "Sequestro/cárcere com lesão grave ou morte" },
  { code: "Art. 158, § 1º", desc: "Extorsão com lesão grave ou morte" },
  { code: "Art. 159, § 1º", desc: "Extorsão mediante sequestro com lesão grave ou morte" },
  { code: "Art. 213, § 1º", desc: "Estupro com resultado lesão grave ou morte" },
  { code: "Art. 217-A, § 3º", desc: "Estupro de vulnerável com resultado lesão grave ou morte" },
  { code: "Lei 11.343/06, Art. 40", desc: "Tráfico de drogas — agravantes especiais" },
  { code: "Art. 61, II, e", desc: "Emprego de veneno, fogo, explosivo, tortura ou meio cruel (majorante implícita)" },
  { code: "Legislação especial", desc: "Outro aumento previsto em lei especial" },
];

export const MINORANTES_LIST: ListItem[] = [
  { code: "Art. 14, II", desc: "Tentativa (redução de 1/3 a 2/3)" },
  { code: "Art. 27", desc: "Participação de menor de 18 anos" },
  { code: "Art. 28", desc: "Coação irresistível ou obediência hierárquica necessária" },
  { code: "Art. 26", desc: "Semi-imputabilidade por desenvolvimento mental incompleto ou retardado (atenuante)" },
  { code: "Art. 65, III, d", desc: "Confissão espontânea (atenuante genérica)" },
  { code: "Art. 155, § 1º", desc: "Furto de pequeno valor (atenuante especial)" },
  { code: "Art. 157, § 3º", desc: "Roubo privilegiado (atenuante especial)" },
  { code: "Art. 121, § 4º", desc: "Homicídio privilegiado (atenuante especial)" },
  { code: "Art. 33, § 4º Lei 11.343/06", desc: "Tráfico privilegiado (cooperação efetiva)" },
  { code: "Art. 23", desc: "Estado de necessidade" },
  { code: "Art. 22", desc: "Legítima defesa putativa (excesso punível)" },
  { code: "Art. 20", desc: "Inimputável — redução de 1/3 a 2/3 (quando não há medida de segurança)" },
  { code: "Art. 68, § 2º", desc: "Causa de diminuição de pena genérica" },
  { code: "Legislação especial", desc: "Outra causa de diminuição prevista em lei especial" },
];

export const SUMULAS: SumulaInfo[] = [
  { id: "Súmula 231/STJ", fase: "2ª fase", cor: "yellow",
    text: "A incidência da circunstância atenuante não pode conduzir à redução da pena abaixo do mínimo legal." },
  { id: "Súmula 241/STJ", fase: "1ª/2ª fase", cor: "yellow",
    text: "A reincidência penal não pode ser considerada como circunstância agravante e, simultaneamente, como circunstância judicial." },
  { id: "Súmula 269/STJ", fase: "Regime", cor: "green",
    text: "É admissível a adoção do regime prisional semi-aberto aos reincidentes condenados a pena igual ou inferior a quatro anos se favoráveis as circunstâncias judiciais." },
  { id: "Súmula 440/STJ", fase: "Regime", cor: "green",
    text: "Fixada a pena-base no mínimo legal, é vedado o estabelecimento de regime prisional mais gravoso do que o cabível em razão da sanção imposta, com base apenas na gravidade abstrata do delito." },
  { id: "Súmula 444/STJ", fase: "1ª fase", cor: "red",
    text: "É vedada a utilização de inquéritos policiais e ações penais em curso para agravar a pena-base." },
  { id: "Súmula 545/STJ", fase: "2ª fase", cor: "yellow",
    text: "Quando a confissão for utilizada para a formação do convencimento do julgador, o réu fará jus à atenuante prevista no art. 65, III, d, do CP." },
  { id: "Súmula 630/STJ", fase: "2ª fase", cor: "yellow",
    text: "A incidência da atenuante da confissão espontânea no crime de tráfico ilícito de entorpecentes exige o reconhecimento da traficância pelo acusado, não bastando a mera admissão da posse para uso próprio." },
  { id: "Súmula 636/STJ", fase: "1ª fase", cor: "red",
    text: "A folha de antecedentes criminais é documento suficiente a comprovar os maus antecedentes e a reincidência." },
  { id: "Súmula 718/STF", fase: "Regime", cor: "green",
    text: "A opinião do julgador sobre a gravidade em abstrato do crime não constitui motivação idônea para a imposição de regime mais severo do que o permitido segundo a pena aplicada." },
  { id: "Súmula 719/STF", fase: "Regime", cor: "green",
    text: "A imposição do regime de cumprimento mais severo do que a pena aplicada permitir exige motivação idônea." },
  { id: "Tema 585/STJ", fase: "2ª fase", cor: "yellow",
    text: "É possível a compensação integral da atenuante da confissão espontânea com a agravante da reincidência, seja ela específica ou não. Nos casos de multirreincidência, deve ser reconhecida a preponderância da reincidência." },
  { id: "Súmula 497/STF", fase: "Prescrição", cor: "blue",
    text: "Quando se tratar de crime continuado, a prescrição regula-se pela pena imposta na sentença, não se computando o acréscimo decorrente da continuação." },
  { id: "Súmula 438/STJ", fase: "Regime", cor: "green",
    text: "O regime prisional semiaberto pode ser substituído pelo aberto, ainda que não preenchidos os requisitos legais, quando o apenado não tiver cometido crime doloso, não for reincidente em crime doloso e tiver cumprido 1/6 da pena." },
  { id: "Súmula 439/STJ", fase: "Regime", cor: "green",
    text: "A progressão de regime prisional exige o cumprimento de 1/6 da pena, salvo reincidente em crime doloso, para quem o percentual é de 1/4." },
  { id: "Súmula 442/STJ", fase: "2ª fase", cor: "yellow",
    text: "A fração de aumento ou diminuição de pena não fixada em lei deve ser fixada pelo juiz, observados os critérios do art. 68 do CP." },
  { id: "Súmula 443/STJ", fase: "1ª/2ª fase", cor: "yellow",
    text: "A majorante da reincidência não se confunde com a circunstância judicial do art. 59, I, do CP." },
  { id: "Súmula 520/STJ", fase: "Regime", cor: "green",
    text: "A progressão de regime prisional independe de requerimento do condenado." },
  { id: "Súmula 527/STJ", fase: "Medida de Segurança", cor: "blue",
    text: "O tempo de duração da medida de segurança não deve ultrapassar o limite máximo da pena abstratamente cominada para o delito praticado." },
  { id: "SV 59/STF", fase: "Dosimetria/Regime", cor: "blue",
    text: "É impositiva a fixação do regime aberto e a substituição da pena por restritivas quando reconhecido tráfico privilegiado e ausentes vetores negativos na 1ª fase." },
  { id: "SV 56/STF", fase: "Regime", cor: "green",
    text: "A falta de estabelecimento penal adequado não autoriza a manutenção do condenado em regime prisional mais gravoso, devendo-se observar os parâmetros fixados no RE 641.320/RS." },
  { id: "SV 26/STF", fase: "Regime", cor: "green",
    text: "Para progressão em crime hediondo, observar inconstitucionalidade do art. 2º da Lei 8.072/1990, sem prejuízo de avaliar requisitos objetivos e subjetivos do benefício." },
  { id: "Súmula 716/STF", fase: "Regime", cor: "green",
    text: "Admite-se progressão de regime antes do trânsito em julgado da sentença condenatória." },
  { id: "Súmula 715/STF", fase: "Execução", cor: "blue",
    text: "A pena unificada para atender ao limite de 30 anos não é considerada para concessão de outros benefícios, como livramento condicional ou regime mais favorável." },
  { id: "Súmula 723/STF", fase: "Sursis", cor: "yellow",
    text: "Não se admite sursis por crime continuado se a soma da pena mínima da infração mais grave com o aumento mínimo de um sexto for superior a um ano." },
  { id: "Súmula 499/STF", fase: "Sursis", cor: "yellow",
    text: "Não obsta à concessão do sursis condenação anterior à pena de multa." },
  { id: "Súmula 711/STF", fase: "Dosimetria", cor: "blue",
    text: "A lei penal mais grave aplica-se ao crime continuado se sua vigência é anterior à cessação da continuidade." },
  { id: "Súmula 604/STF", fase: "Prescrição", cor: "blue",
    text: "A prescrição pela pena em concreto é somente da pretensão executória da pena privativa de liberdade." },
];

export const PRESCRICAO: PrescricaoFaixa[] = [
  { faixa: "Acima de 12 anos", prazo: 20 },
  { faixa: "Acima de 8 até 12 anos", prazo: 16 },
  { faixa: "Acima de 4 até 8 anos", prazo: 12 },
  { faixa: "Acima de 2 até 4 anos", prazo: 8 },
  { faixa: "1 ano até 2 anos", prazo: 4 },
  { faixa: "Inferior a 1 ano", prazo: 3 },
];

export const FRACS = ["1/8","1/6","1/5","1/4","1/3","1/2"] as const;

export const COLOR_MAP: Record<Color, string> = {
  blue: "bg-blue-50 border-blue-200 text-blue-800",
  yellow: "bg-yellow-50 border-yellow-200 text-yellow-800",
  red: "bg-red-50 border-red-200 text-red-800",
  green: "bg-green-50 border-green-200 text-green-800",
  gray: "bg-gray-50 border-gray-200 text-gray-700",
};

export const PILL_MAP: Record<Color, string> = {
  red: "bg-red-100 text-red-700",
  green: "bg-green-100 text-green-700",
  yellow: "bg-yellow-100 text-yellow-700",
  blue: "bg-blue-100 text-blue-700",
  gray: "bg-gray-100 text-gray-600",
};
